/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wechat_hacker_root */

#ifndef _Included_wechat_hacker_root
#define _Included_wechat_hacker_root
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wechat_hacker_root
 * Method:    try_root
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_wechat_hacker_root_try_1root
  (JNIEnv *, jclass);

/*
 * Class:     wechat_hacker_root
 * Method:    root_shell
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_wechat_hacker_root_root_1shell
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
